# Generated by Django 4.1.13 on 2026-02-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_user_role_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
    ]
